sudo: required
services:
    - docker


berfore_install:
    - docker build -t pthirannamur/docker-react -f Dockerfile.dev .

    
script: 
    - docker run -e CI=true pthirannamur/docker-react npm run test